language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
  - stage: build
    script: ./gradlew build --scan -s
  - stage: deploy
    if: branch = master
    script: ./gradlew bintrayUpload
