name: Publish to bintray

on:
  release:
    types: [prereleased, published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish to Github
      env:
        GPR_USER: 'yarinvak'
        GPR_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew publish
    - name: Publish to Bintray
      env:
        BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
      run: ./gradlew bintrayUpload
